spring.application.name=tweet-service
server.port=8083
spring.profiles.active=${APP_PROFILE:test}

cloud.aws.credentials.access-key=${AWS_ACCESS_KEY_ID:accessKey}
cloud.aws.credentials.secret-key=${AWS_SECRET_ACCESS_KEY:secretKey}
cloud.aws.region.static=${AWS_REGION:us-east-1}
aws.s3.bucket-name=${AWS_S3_BUCKET:bucketName}

aws.sns.tweet-event.topic-arn=${AWS_SNS_TWEET_EVENT_TOPIC_ARN:arn}

aws.sqs.like-events-queue-url=${AWS_SQS_LIKE_EVENTS_QUEUE_URL:url}
aws.sqs.like-events-queue-dlq-url=${AWS_SQS_LIKE_EVENTS_QUEUE_DLQ_URL:url}

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true