spring.application.name=user-service
server.port=8082
spring.profiles.active=${APP_PROFILE:test}

cloud.aws.credentials.access-key=${AWS_ACCESS_KEY_ID:accessKey}
cloud.aws.credentials.secret-key=${AWS_SECRET_ACCESS_KEY:secretKey}
cloud.aws.region.static=${AWS_REGION:us-east-1}
aws.s3.bucket-name=${AWS_S3_BUCKET:bucketName}

aws.sns.high-followers-topic-arn=${AWS_SNS_HIGH_FOLLOWERS_TOPIC_ARN:arn}

aws.sqs.user-follow-events-queue-url=${AWS_SQS_USER_FOLLOW_EVENTS_QUEUE_URL:url}
aws.sqs.user-follow-events-queue-dlq-url=${AWS_SQS_USER_FOLLOW_EVENTS_QUEUE_DLQ_URL:url}

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true