spring.application.name=feed-service
server.port=8086

cloud.aws.credentials.access-key=${AWS_ACCESS_KEY_ID:accessKey}
cloud.aws.credentials.secret-key=${AWS_SECRET_ACCESS_KEY:secretKey}
cloud.aws.region.static=${AWS_REGION:us-east-1}

spring.profiles.active=${APP_PROFILE:test}

feed.user.table=${FEED_USER_TABLE:user-table}
feed.global.table=${FEED_GLOBAL_TABLE:global-table}

feed.max-limit=${FEED_MAX_LIMIT:100}

aws.sqs.tweet-events-queue-url=${AWS_SQS_TWEET_EVENTS_QUEUE_URL:url}
aws.sqs.tweet-events-dlq-queue-url=${AWS_SQS_TWEET_EVENTS_DLQ_QUEUE_URL:url}

aws.sqs.follow-events-queue-url=${AWS_SQS_FOLLOW_EVENTS_QUEUE_URL:url}
aws.sqs.follow-events-dlq-queue-url=${AWS_SQS_FOLLOW_EVENTS_DLQ_QUEUE_URL:url}

aws.sqs.high-followers-queue-url=${AWS_SQS_HIGH_FOLLOWERS_QUEUE_URL:url}
aws.sqs.high-followers-dlq-queue-url=${AWS_SQS_HIGH_FOLLOWERS_DLQ_QUEUE_URL:url}

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true