spring.application.name=like-service
server.port=8085

spring.profiles.active=${APP_PROFILE:test}

cloud.aws.credentials.access-key=${AWS_ACCESS_KEY_ID:accessKey}
cloud.aws.credentials.secret-key=${AWS_SECRET_ACCESS_KEY:secretKey}
cloud.aws.region.static=${AWS_REGION:us-east-1}

aws.sns.like-event.topic-arn=${AWS_SNS_LIKE_EVENT_TOPIC_ARN:arn}

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true